# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: CC0000
    description: An issue with the system ğŸ›.
    
  - name: feature
    color: 336699
    description: New functionality.
    
  - name: first-timers-only
    # include the old name to rename an existing label
    oldname: Help Wanted
